spring:
  application:
    name: northbound-service
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.2.16:8848
      username: nacos
      password: nacos
  profiles:
    active: dev
server:
  port: 9090
