spring:
  application:
    name: northbound-service
#  cloud:
#    nacos:
#      discovery:
#        server-addr: 192.168.2.16:8848
#      username: nacos
#      password: nacos
  profiles:
    active: dev
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
  jackson:
    time-zone: Asia/Shanghai
server:
  port: 9090
mybatis:
  configuration:
    map-underscore-to-camel-case: true
