spring:
  datasource:
    username: monkey
    password: 123456
    url: jdbc:mysql://192.168.2.16:3306/sdwan_controller?useUnicode=true
  cloud:
    nacos:
      discovery:
        namespace: 1831d545-4c1a-492b-b473-128b7207379d